package controller;

public enum UserType {
	USER,
	CUSTOMER,
	STATION_MANAGER,
	MARKETING_DEPARTMENT_WORKER,
	CHAIN_MANAGER,
	FUEL_SUPPLIER,
	MARKETING_REPRESENTATIVE,
	MARKETING_MANAGER,
	SUPPLIER
	
}
